ALTER TABLE support_tickets
  ADD COLUMN IF NOT EXISTS answer_file_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS answer_file_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS answer_file_type VARCHAR(20) NOT NULL DEFAULT '';