ALTER TABLE support_tickets
  ADD COLUMN IF NOT EXISTS file_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS file_type VARCHAR(20) NOT NULL DEFAULT '';