ALTER TABLE support_tickets
  ADD COLUMN IF NOT EXISTS closed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS closed_by INTEGER REFERENCES users(id);